function Initialize_dialog
Pix_SS = get(0,'screensize');

d = dialog('Position',[Pix_SS(3)./2-125 Pix_SS(4)./2+150 250 80],'Name','SLM...');

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 30 210 40],...
    'String','Please setup the SLM and Beams Phase parameters.');

btn = uicontrol('Parent',d,...
    'Position',[95 11 70 25],...
    'String','Close',...
    'Callback','delete(gcf)');
